// Generated by   : ImageConverter 565 Online
// Generated from : vendingland ttgo logo.png
// Time generated : Sun, 29 Jan 23 13:53:15 +0100  (Server timezone: CET)
// Image Size     : 240x135 pixels
// Memory usage   : 64800 bytes


#if defined(__AVR__)
    #include <avr/pgmspace.h>
#elif defined(__PIC32MX__)
    #define PROGMEM
#elif defined(__arm__)
    #define PROGMEM
#endif

const uint16_t infoWidth = 240;
const uint16_t infoHeight = 135;

const unsigned short ttgo_logo[32400] PROGMEM={};
